-- PostgreSQL 切库基线：当前不在 Flyway 默认扫描目录，未验证前不得切换运行配置。
-- 全表主键由 Identity 自增；状态码、长度、关联归属与发布条件仍先由 Service 校验。
-- 除唯一索引及 ON DELETE RESTRICT 外，不用数据库 CHECK/级联删除承载业务规则。

-- 账号与公共资源：正常访客账号可读公开内容，只有 OWNER 能进入管理接口。

CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    type SMALLINT NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status SMALLINT NOT NULL,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX uk_user_account_username_ci ON user_account (LOWER(username));

CREATE TABLE media_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_type SMALLINT NOT NULL,
    storage_key VARCHAR(512),
    source_type SMALLINT NOT NULL,
    source_host VARCHAR(255),
    original_filename VARCHAR(255),
    mime_type VARCHAR(100),
    byte_size BIGINT,
    sha256 BYTEA,
    width INTEGER,
    height INTEGER,
    status SMALLINT NOT NULL,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_media_asset_storage_key UNIQUE (storage_key)
);
CREATE INDEX idx_media_asset_status_created ON media_asset (status, created_at);

-- 公开资料和技术/主题标签不保存博客正文。
CREATE TABLE site_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    headline VARCHAR(200) NOT NULL,
    intro TEXT NOT NULL,
    github_url VARCHAR(2048),
    email VARCHAR(254),
    avatar_media_id BIGINT,
    resume_media_id BIGINT,
    seo_title VARCHAR(200),
    seo_description VARCHAR(500),
    updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_site_config_avatar FOREIGN KEY (avatar_media_id)
        REFERENCES media_asset (id) ON DELETE RESTRICT,
    CONSTRAINT fk_site_config_resume FOREIGN KEY (resume_media_id)
        REFERENCES media_asset (id) ON DELETE RESTRICT
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind SMALLINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    group_code SMALLINT,
    logo_key VARCHAR(160),
    is_featured SMALLINT NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT uk_tag_kind_name UNIQUE (kind, normalized_name)
);
CREATE UNIQUE INDEX uk_tag_slug_ci ON tag (LOWER(slug));
CREATE INDEX idx_tag_display ON tag (kind, group_code, is_featured, sort_order);

-- 项目仅保存展示资料、外链、标签和媒体关系，不上传项目源码。
CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(160),
    title VARCHAR(200),
    summary TEXT,
    contribution TEXT,
    outcome TEXT,
    time_label VARCHAR(100),
    status SMALLINT NOT NULL,
    is_featured SMALLINT NOT NULL,
    sort_order INTEGER NOT NULL,
    version BIGINT NOT NULL,
    published_at TIMESTAMP(3) WITHOUT TIME ZONE,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX uk_project_slug_ci ON project (LOWER(slug));
CREATE INDEX idx_project_featured ON project (status, is_featured, sort_order, id);
CREATE INDEX idx_project_published ON project (status, published_at, id);

CREATE TABLE project_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    link_type SMALLINT NOT NULL,
    label VARCHAR(100),
    url VARCHAR(2048) NOT NULL,
    is_visible SMALLINT NOT NULL,
    sort_order INTEGER NOT NULL,
    CONSTRAINT fk_project_link_project FOREIGN KEY (project_id)
        REFERENCES project (id) ON DELETE RESTRICT
);
CREATE INDEX idx_project_link_order ON project_link (project_id, sort_order, id);

CREATE TABLE project_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT uk_project_tag_pair UNIQUE (project_id, tag_id),
    CONSTRAINT fk_project_tag_project FOREIGN KEY (project_id)
        REFERENCES project (id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_tag_tag FOREIGN KEY (tag_id)
        REFERENCES tag (id) ON DELETE RESTRICT
);
CREATE INDEX idx_project_tag_reverse ON project_tag (tag_id, project_id);

CREATE TABLE project_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    media_id BIGINT NOT NULL,
    role SMALLINT NOT NULL,
    alt_text VARCHAR(500),
    sort_order INTEGER NOT NULL,
    CONSTRAINT uk_project_media_relation UNIQUE (project_id, media_id, role),
    CONSTRAINT fk_project_media_project FOREIGN KEY (project_id)
        REFERENCES project (id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_media_media FOREIGN KEY (media_id)
        REFERENCES media_asset (id) ON DELETE RESTRICT
);
CREATE INDEX idx_project_media_reverse ON project_media (media_id, project_id);

-- Document 是内容身份；current_version_id 只代表站长最近保存的版本，不代表公开版本。
CREATE TABLE document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    origin_type SMALLINT NOT NULL,
    current_version_id BIGINT,
    lock_version BIGINT NOT NULL,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_document_owner FOREIGN KEY (owner_id)
        REFERENCES user_account (id) ON DELETE RESTRICT
);

CREATE TABLE document_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_number BIGINT NOT NULL,
    title VARCHAR(200),
    summary TEXT,
    markdown_content TEXT NOT NULL,
    reading_time_minutes SMALLINT NOT NULL,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_document_version_number UNIQUE (document_id, version_number),
    CONSTRAINT fk_document_version_document FOREIGN KEY (document_id)
        REFERENCES document (id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_version_author FOREIGN KEY (created_by)
        REFERENCES user_account (id) ON DELETE RESTRICT
);
CREATE INDEX idx_document_version_recent ON document_version (document_id, created_at DESC, id DESC);
-- Document 与 Version 相互引用，先建两表，再补当前版本外键；新文档可先插入 NULL 指针。
ALTER TABLE document ADD CONSTRAINT fk_document_current_version
    FOREIGN KEY (current_version_id) REFERENCES document_version (id) ON DELETE RESTRICT;

-- 版本资源清单包含正文引用和封面；READY Asset 不允许原地覆盖存储对象。
CREATE TABLE document_version_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id BIGINT NOT NULL,
    media_id BIGINT NOT NULL,
    role SMALLINT NOT NULL,
    alt_text VARCHAR(500),
    source_reference VARCHAR(2048),
    sort_order INTEGER NOT NULL,
    CONSTRAINT fk_document_asset_version FOREIGN KEY (document_version_id)
        REFERENCES document_version (id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_asset_media FOREIGN KEY (media_id)
        REFERENCES media_asset (id) ON DELETE RESTRICT
);
CREATE INDEX idx_document_asset_order ON document_version_asset (document_version_id, sort_order, id);
CREATE INDEX idx_document_asset_media ON document_version_asset (media_id, document_version_id);

-- 保留当时显示的标签名称和 slug；Tag 全局改名不得改变已发布旧版本。
CREATE TABLE document_version_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    tag_name_snapshot VARCHAR(100) NOT NULL,
    tag_slug_snapshot VARCHAR(120) NOT NULL,
    CONSTRAINT uk_document_version_tag_pair UNIQUE (document_version_id, tag_id),
    CONSTRAINT fk_document_tag_version FOREIGN KEY (document_version_id)
        REFERENCES document_version (id) ON DELETE RESTRICT,
    CONSTRAINT fk_document_tag_tag FOREIGN KEY (tag_id)
        REFERENCES tag (id) ON DELETE RESTRICT
);
CREATE INDEX idx_document_tag_reverse ON document_version_tag (tag_id, document_version_id);

-- 公开读只使用 published_version_id；编辑保存不改变它，显式重新发布才切换。
CREATE TABLE blog_post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    published_version_id BIGINT,
    slug VARCHAR(160),
    status SMALLINT NOT NULL,
    allow_visitor_download SMALLINT NOT NULL,
    published_at TIMESTAMP(3) WITHOUT TIME ZONE,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uk_blog_post_document UNIQUE (document_id),
    CONSTRAINT fk_blog_post_document FOREIGN KEY (document_id)
        REFERENCES document (id) ON DELETE RESTRICT,
    CONSTRAINT fk_blog_post_published_version FOREIGN KEY (published_version_id)
        REFERENCES document_version (id) ON DELETE RESTRICT
);
CREATE UNIQUE INDEX uk_blog_post_slug_ci ON blog_post (LOWER(slug));
CREATE INDEX idx_blog_post_published ON blog_post (status, published_at DESC, id DESC);

-- 导入问题记录不保存 Word/PDF 原文件，格式扩展由 Importer 边界负责。
CREATE TABLE document_import_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    document_version_id BIGINT,
    source_format SMALLINT NOT NULL,
    original_filename VARCHAR(255),
    status SMALLINT NOT NULL,
    issues_json JSONB,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_import_job_document FOREIGN KEY (document_id)
        REFERENCES document (id) ON DELETE RESTRICT,
    CONSTRAINT fk_import_job_version FOREIGN KEY (document_version_id)
        REFERENCES document_version (id) ON DELETE RESTRICT
);
CREATE INDEX idx_document_import_job_document ON document_import_job (document_id, created_at DESC);

-- TaskExecutor 负责执行；本表负责持久化重试与定时恢复状态，不把 Redis 当任务真源。
CREATE TABLE document_processing_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id BIGINT NOT NULL,
    task_type SMALLINT NOT NULL,
    status SMALLINT NOT NULL,
    retry_count INTEGER NOT NULL,
    max_retry_count INTEGER NOT NULL,
    next_retry_at TIMESTAMP(3) WITHOUT TIME ZONE,
    started_at TIMESTAMP(3) WITHOUT TIME ZONE,
    finished_at TIMESTAMP(3) WITHOUT TIME ZONE,
    error_message VARCHAR(1000),
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_processing_task_version FOREIGN KEY (document_version_id)
        REFERENCES document_version (id) ON DELETE RESTRICT
);
CREATE INDEX idx_processing_task_due ON document_processing_task (status, next_retry_at, id);

-- 数据库级 description：按表和字段顺序排列，便于 DBA 与元数据工具直接查看。

-- user_account
COMMENT ON TABLE user_account IS '站长与普通访客账号；普通账号不得获取管理权限';
COMMENT ON COLUMN user_account.id IS '账号自增主键；仅用于站内关联';
COMMENT ON COLUMN user_account.username IS '登录用户名；按小写唯一索引避免大小写重复';
COMMENT ON COLUMN user_account.type IS '账号类型数值码：0=站长，1=普通访客；由服务端枚举校验';
COMMENT ON COLUMN user_account.password_hash IS '服务端持久化的密码摘要；不得返回接口或写入日志';
COMMENT ON COLUMN user_account.status IS '账号状态数值码：0=禁用，1=启用';
COMMENT ON COLUMN user_account.created_at IS '账号创建时间；应用写入 UTC，精度毫秒';
COMMENT ON COLUMN user_account.updated_at IS '账号资料或状态最后更新时间；应用写入 UTC，精度毫秒';

-- media_asset
COMMENT ON TABLE media_asset IS '受控二进制资源元数据；实际字节由对象存储管理';
COMMENT ON COLUMN media_asset.id IS '资源自增主键；asset:// 引用中的内部资源 ID，不代表公开授权';
COMMENT ON COLUMN media_asset.asset_type IS '资源类别数值码：0=图片，1=文档；后续音视频须扩展服务端枚举';
COMMENT ON COLUMN media_asset.storage_key IS '对象存储键；资源 READY 后不得原地覆盖';
COMMENT ON COLUMN media_asset.source_type IS '资源来源数值码：0=本地笔记，1=网络地址，2=编辑器上传';
COMMENT ON COLUMN media_asset.source_host IS '网络来源的主机名；不保存查询参数、令牌或完整 URL';
COMMENT ON COLUMN media_asset.original_filename IS '上传或导入时的原始文件名；仅用于展示与审计';
COMMENT ON COLUMN media_asset.mime_type IS '经服务端内容校验后的媒体 MIME 类型';
COMMENT ON COLUMN media_asset.byte_size IS '二进制对象大小，单位字节';
COMMENT ON COLUMN media_asset.sha256 IS '二进制对象的 SHA-256 摘要，原始 32 字节';
COMMENT ON COLUMN media_asset.width IS '图片像素宽度；非图片可为空';
COMMENT ON COLUMN media_asset.height IS '图片像素高度；非图片可为空';
COMMENT ON COLUMN media_asset.status IS '资源状态数值码：0=待处理，1=可用，2=失败；只有可用资源可进入公开版本';
COMMENT ON COLUMN media_asset.created_at IS '资源记录创建时间；应用写入 UTC，精度毫秒';
COMMENT ON COLUMN media_asset.updated_at IS '资源状态或元数据最后更新时间；应用写入 UTC，精度毫秒';

-- site_config
COMMENT ON TABLE site_config IS '站点主人批准公开的个人资料和联系入口';
COMMENT ON COLUMN site_config.id IS '站点资料自增主键；当前业务仅维护一条配置';
COMMENT ON COLUMN site_config.display_name IS '首页公开显示的站点主人昵称或名称';
COMMENT ON COLUMN site_config.headline IS '首页公开显示的职业定位或一句话介绍';
COMMENT ON COLUMN site_config.intro IS '首页公开显示的详细自我介绍';
COMMENT ON COLUMN site_config.github_url IS '经站点主人批准公开的 GitHub 主页 HTTPS 地址';
COMMENT ON COLUMN site_config.email IS '经站点主人批准公开的联系邮箱';
COMMENT ON COLUMN site_config.avatar_media_id IS '公开头像对应的 media_asset.id；未上传时为空';
COMMENT ON COLUMN site_config.resume_media_id IS '公开简历对应的 media_asset.id；未上传时为空';
COMMENT ON COLUMN site_config.seo_title IS '站点默认搜索结果标题；页面可按内容覆盖';
COMMENT ON COLUMN site_config.seo_description IS '站点默认搜索结果摘要；页面可按内容覆盖';
COMMENT ON COLUMN site_config.updated_at IS '站点资料最后更新时间；应用写入 UTC，精度毫秒';

-- tag
COMMENT ON TABLE tag IS '文章主题及技术栈等全局标签';
COMMENT ON COLUMN tag.id IS '全局标签自增主键；项目或文档版本通过此 ID 关联';
COMMENT ON COLUMN tag.kind IS '标签类别数值码：0=文章主题，1=技术能力';
COMMENT ON COLUMN tag.name IS '当前全局展示名称；已发布文档使用版本内名称快照';
COMMENT ON COLUMN tag.normalized_name IS '服务端规范化后的名称，用于同类标签去重';
COMMENT ON COLUMN tag.slug IS '标签稳定公开标识；被公开版本引用后不得改写';
COMMENT ON COLUMN tag.group_code IS '技术标签分组数值码：0=语言，1=框架，2=工具，3=基础设施，4=数据技术；主题标签为空';
COMMENT ON COLUMN tag.logo_key IS '技术 Logo 的受控静态资源键；不是任意网络地址';
COMMENT ON COLUMN tag.is_featured IS '是否在首页重点展示：0=否，1=是';
COMMENT ON COLUMN tag.sort_order IS '同组标签展示顺序；数值越小越靠前';

-- project
COMMENT ON TABLE project IS '项目展示资料；不保存源码或项目文件夹';
COMMENT ON COLUMN project.id IS '项目展示记录自增主键；不对应源码文件';
COMMENT ON COLUMN project.slug IS '项目稳定公开标识；草稿可为空，发布前必须填写';
COMMENT ON COLUMN project.title IS '项目展示标题；草稿可为空，发布前必须填写';
COMMENT ON COLUMN project.summary IS '项目简要介绍；草稿可为空，发布前必须填写';
COMMENT ON COLUMN project.contribution IS '站点主人在项目中的具体贡献；草稿可为空';
COMMENT ON COLUMN project.outcome IS '项目成果或可验证产出；没有时可为空';
COMMENT ON COLUMN project.time_label IS '展示用时间文字，不强迫不确定的日期精度';
COMMENT ON COLUMN project.status IS '项目状态数值码：0=草稿或已下架，1=已发布；服务端控制转换';
COMMENT ON COLUMN project.is_featured IS '是否作为首页重点项目：0=否，1=是';
COMMENT ON COLUMN project.sort_order IS '项目展示顺序；数值越小越靠前';
COMMENT ON COLUMN project.version IS '项目乐观锁计数，不是内容历史版本号';
COMMENT ON COLUMN project.published_at IS '最近一次进入已发布状态的 UTC 时间；首次发布前为空，下架后保留历史值';
COMMENT ON COLUMN project.created_at IS '项目创建时间；应用写入 UTC，精度毫秒';
COMMENT ON COLUMN project.updated_at IS '项目最后更新时间；应用写入 UTC，精度毫秒';

-- project_link
COMMENT ON TABLE project_link IS '项目外部代码、演示等入口';
COMMENT ON COLUMN project_link.id IS '项目外链关系自增主键';
COMMENT ON COLUMN project_link.project_id IS '所属 project.id；服务端先校验目标存在';
COMMENT ON COLUMN project_link.link_type IS '入口类型数值码：0=代码仓库，1=在线演示，2=文档，3=其他';
COMMENT ON COLUMN project_link.label IS '按钮或链接显示文字；为空时由类型生成默认文字';
COMMENT ON COLUMN project_link.url IS '外部目标地址；服务端仅接受 HTTP 或 HTTPS';
COMMENT ON COLUMN project_link.is_visible IS '是否向访客展示：0=隐藏，1=展示';
COMMENT ON COLUMN project_link.sort_order IS '同一项目外链展示顺序；数值越小越靠前';

-- project_tag
COMMENT ON TABLE project_tag IS '项目与全局技术/主题标签关联';
COMMENT ON COLUMN project_tag.id IS '项目标签关系自增主键';
COMMENT ON COLUMN project_tag.project_id IS '所属 project.id';
COMMENT ON COLUMN project_tag.tag_id IS '关联 tag.id；同一项目与标签组合不得重复';

-- project_media
COMMENT ON TABLE project_media IS '项目展示图片与封面关系';
COMMENT ON COLUMN project_media.id IS '项目资源关系自增主键';
COMMENT ON COLUMN project_media.project_id IS '所属 project.id';
COMMENT ON COLUMN project_media.media_id IS '关联 media_asset.id；公开读取仍须校验项目已发布';
COMMENT ON COLUMN project_media.role IS '资源用途数值码：0=图集，1=封面；服务端限制单项目封面数量';
COMMENT ON COLUMN project_media.alt_text IS '该项目语境下的图片替代文字';
COMMENT ON COLUMN project_media.sort_order IS '同一项目媒体展示顺序；数值越小越靠前';

-- document
COMMENT ON TABLE document IS '统一文档身份；当前版本可能仍是未发布草稿';
COMMENT ON COLUMN document.id IS '统一文档自增主键；同一文档可产生多个不可变版本';
COMMENT ON COLUMN document.owner_id IS '文档所有者 user_account.id；首版仅站长可编辑';
COMMENT ON COLUMN document.origin_type IS '创建来源数值码：0=站内创建，1=导入；不决定正文模型';
COMMENT ON COLUMN document.current_version_id IS '最新已保存版本；不可据此判断访客可见性';
COMMENT ON COLUMN document.lock_version IS '文档写入乐观锁计数；与内容版本号不同';
COMMENT ON COLUMN document.created_at IS '文档身份创建时间；应用写入 UTC，精度毫秒';
COMMENT ON COLUMN document.updated_at IS '文档最新保存时间；不等于公开重新发布时间';

-- document_version
COMMENT ON TABLE document_version IS '不可变文档快照：Markdown、标题、摘要和派生阅读时长';
COMMENT ON COLUMN document_version.id IS '不可变内容版本自增主键；供博客发布指针和后续索引引用';
COMMENT ON COLUMN document_version.document_id IS '所属 document.id；一个文档对应多个版本';
COMMENT ON COLUMN document_version.version_number IS '同一文档内单调增加的内容版本号';
COMMENT ON COLUMN document_version.title IS '此版本的标题快照；草稿可为空，发布前必填';
COMMENT ON COLUMN document_version.summary IS '此版本的摘要快照；草稿可为空，发布前必填';
COMMENT ON COLUMN document_version.markdown_content IS '此版本唯一可编辑正文真源；图片和附件使用 asset:// 内部引用';
COMMENT ON COLUMN document_version.reading_time_minutes IS '从本版本正文计算；草稿保存不改变已发布版本的阅读时长';
COMMENT ON COLUMN document_version.created_by IS '创建该版本的 user_account.id';
COMMENT ON COLUMN document_version.created_at IS '此版本创建时间；写入后不得修改';

-- document_version_asset
COMMENT ON TABLE document_version_asset IS '某一文档版本实际使用的 Asset 清单及呈现信息';
COMMENT ON COLUMN document_version_asset.id IS '版本资源关系自增主键';
COMMENT ON COLUMN document_version_asset.document_version_id IS '使用资源的 document_version.id；关联写入后不可修改';
COMMENT ON COLUMN document_version_asset.media_id IS '该版本引用的 media_asset.id；须为已授权 READY 资源';
COMMENT ON COLUMN document_version_asset.role IS '此版本中的资源用途数值码：0=正文内嵌，1=封面，2=社交分享图';
COMMENT ON COLUMN document_version_asset.alt_text IS '此版本语境下的图片替代文字快照';
COMMENT ON COLUMN document_version_asset.source_reference IS '导入前的本地路径或网络引用；仅供问题定位，不作为浏览器加载地址';
COMMENT ON COLUMN document_version_asset.sort_order IS '同一版本资源展示顺序；数值越小越靠前';

-- document_version_tag
COMMENT ON TABLE document_version_tag IS '某一文档版本使用的标签及当时的显示快照';
COMMENT ON COLUMN document_version_tag.id IS '版本标签关系自增主键';
COMMENT ON COLUMN document_version_tag.document_version_id IS '所属 document_version.id；关联写入后不可修改';
COMMENT ON COLUMN document_version_tag.tag_id IS '来源 tag.id；展示名称和 slug 使用同一行快照字段';
COMMENT ON COLUMN document_version_tag.tag_name_snapshot IS '本版本展示用名称，不随全局 Tag 修改而改变';
COMMENT ON COLUMN document_version_tag.tag_slug_snapshot IS '本版本展示用 slug，不随全局 Tag 修改而改变';

-- blog_post
COMMENT ON TABLE blog_post IS 'Document 的博客发布视图；不重复保存正文';
COMMENT ON COLUMN blog_post.id IS '博客发布记录自增主键；不存第二份正文';
COMMENT ON COLUMN blog_post.document_id IS '对应 document.id；同一文档最多一条博客发布记录';
COMMENT ON COLUMN blog_post.published_version_id IS '访客可见的版本指针；只在显式发布时切换';
COMMENT ON COLUMN blog_post.slug IS '博客稳定公开路径标识；草稿可为空，发布前必须填写';
COMMENT ON COLUMN blog_post.status IS '博客状态数值码：0=草稿或已下架，1=已发布；公开读取须同时检查状态和版本';
COMMENT ON COLUMN blog_post.allow_visitor_download IS '逐篇下载开关；普通访客仍须登录且账号有效';
COMMENT ON COLUMN blog_post.published_at IS '最近一次显式发布或重新发布的 UTC 时间；首次发布前为空，下架后保留历史值';
COMMENT ON COLUMN blog_post.created_at IS '博客发布记录创建时间；不代表首次公开时间';
COMMENT ON COLUMN blog_post.updated_at IS '博客发布信息最后更新时间；保存文档草稿不更新此字段';

-- document_import_job
COMMENT ON TABLE document_import_job IS '格式导入任务及解析问题记录';
COMMENT ON COLUMN document_import_job.id IS '文档导入任务自增主键';
COMMENT ON COLUMN document_import_job.document_id IS '导入产生或更新的 document.id；导入失败前可为空';
COMMENT ON COLUMN document_import_job.document_version_id IS '导入成功生成的 document_version.id；未生成版本时为空';
COMMENT ON COLUMN document_import_job.source_format IS '导入格式数值码：0=Markdown，1=Word，2=PDF；首版仅注册 Markdown Importer';
COMMENT ON COLUMN document_import_job.original_filename IS '导入文件的原始文件名；不保存原文件字节';
COMMENT ON COLUMN document_import_job.status IS '导入任务生命周期状态：待处理、处理中、完成或失败；具体数值码待服务端枚举定稿';
COMMENT ON COLUMN document_import_job.issues_json IS '解析警告或错误的结构化问题清单；不得包含凭据或敏感 URL';
COMMENT ON COLUMN document_import_job.created_at IS '导入任务创建时间；应用写入 UTC，精度毫秒';
COMMENT ON COLUMN document_import_job.updated_at IS '导入任务最后状态更新时间；应用写入 UTC，精度毫秒';

-- document_processing_task
COMMENT ON TABLE document_processing_task IS '异步处理任务的持久状态、重试与恢复依据';
COMMENT ON COLUMN document_processing_task.id IS '异步处理任务自增主键';
COMMENT ON COLUMN document_processing_task.document_version_id IS '本次处理所针对的不可变 document_version.id';
COMMENT ON COLUMN document_processing_task.task_type IS '处理任务类别数值码，例如索引构建';
COMMENT ON COLUMN document_processing_task.status IS '异步任务生命周期状态：待处理、处理中、等待重试、成功或失败；具体数值码待服务端枚举定稿';
COMMENT ON COLUMN document_processing_task.retry_count IS '已经执行的重试次数；由任务服务更新';
COMMENT ON COLUMN document_processing_task.max_retry_count IS '允许的最大重试次数；达到后标记最终失败';
COMMENT ON COLUMN document_processing_task.next_retry_at IS '下一次允许重试的 UTC 时间；非等待状态可为空';
COMMENT ON COLUMN document_processing_task.started_at IS '最近一次开始处理的 UTC 时间；未开始时为空';
COMMENT ON COLUMN document_processing_task.finished_at IS '最终成功或失败的 UTC 时间；未结束时为空';
COMMENT ON COLUMN document_processing_task.error_message IS '供排障的安全错误摘要；不得保存密钥、原始凭据或完整敏感载荷';
COMMENT ON COLUMN document_processing_task.created_at IS '任务入库时间；应用写入 UTC，精度毫秒';
COMMENT ON COLUMN document_processing_task.updated_at IS '任务状态最后更新时间；应用写入 UTC，精度毫秒';
