-- 个人中心独立于首页站长展示资料 site_config；不重写已发布的 V1 基线。
-- 首次修改资料时由服务端创建，账号行锁保证并发创建同一资料不会冲突。
-- 校验昵称、账号归属、图片类型和可用状态均由 Service 完成，不用 CHECK 兜底。
CREATE TABLE user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    nickname VARCHAR(64),
    avatar_media_id BIGINT,
    created_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(3) WITHOUT TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX uk_user_profile_account ON user_profile (account_id);

COMMENT ON TABLE user_profile IS '登录账号本人维护的个人资料；与公开站长资料 site_config 无关';
COMMENT ON COLUMN user_profile.id IS '个人资料自增主键';
COMMENT ON COLUMN user_profile.account_id IS '所属 user_account.id；服务端以当前会话确定，不接受客户端指定';
COMMENT ON COLUMN user_profile.nickname IS '账号显示昵称；服务端限制 64 个 Unicode 字符，空值显示登录用户名';
COMMENT ON COLUMN user_profile.avatar_media_id IS '本人头像对应的 READY 图片 media_asset.id；未上传为空，不授予其他账号读取权限';
COMMENT ON COLUMN user_profile.created_at IS '首次维护个人资料的 UTC 时间，精度毫秒';
COMMENT ON COLUMN user_profile.updated_at IS '昵称或头像最近修改的 UTC 时间，精度毫秒';
