<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.amai</groupId>
        <artifactId>mai-portfolio</artifactId>
        <version>0.1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>mai-portfolio-modules</artifactId>
    <packaging>pom</packaging>
    <name>mai-portfolio-modules</name>
    <modules>
        <module>mai-portfolio-module-system</module>
        <module>mai-portfolio-module-portfolio</module>
        <module>mai-portfolio-module-asset</module>
        <module>mai-portfolio-module-blog</module>
        <module>mai-portfolio-module-agent</module>
    </modules>
</project>
